HalfFull/urls.py
from django.urls import path
from HalfFull import views

app_name = 'HalfFull'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name ='contact'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('userpage/', views.userpage, name='userpage'),
    path('make_a_crawl/', views.make_a_crawl, name='make_a_crawl'),
    path('pub_list/', views.pub_list, name='pub_list'),
    path('add_a_pub/', views.add_a_pub, name='add_a_pub'),
]

Half_Full_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from HalfFull import views

urlpatterns = [
    path('', views.home, name='home'),
    path('HalfFull/', include('HalfFull.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),

]

HalfFull/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pub(models.Model):
    name = models.CharField(max_length=128, unique=True)
    
    drinks = models.IntegerField(default=0)
    atmosphere = models.IntegerField(default=0)
    service = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='pub_images', blank=True)
    
    def __str__(self): 
        return self.name
        
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    crawl = models.ManyToManyField(Pub)
    def __str__(self):
        return self.user.username

HalfFull/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.models import User 
from HalfFull.models import UserProfile, Pub

class UserForm(forms.ModelForm): 
    
    class Meta: 
        model = User 
        fields = ('username', 'email', 'password',)

    password = forms.CharField(widget=forms.PasswordInput())
    
#class CrawlForm(forms.ModelForm):
#    class Meta:
#        model = UserProfile
#        fields = ('crawl',)
        
class PubForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the pub name.")
    drinks = forms.IntegerField(min_value = 0, max_value=5, help_text="how would you rate this pubs drinks") 
    atmosphere = forms.IntegerField(min_value = 0, max_value=5, help_text="how would you rate this pubs atmosphere")
    service = forms.IntegerField(min_value = 0, max_value=5, help_text="how would you rate the service of this pub")
    
    #slug = forms.CharField(widget=forms.HiddenInput(), required=False) 
    
    class Meta: 
        model = Pub 
        fields = ('name', 'picture',)
        

        

HalfFull/views.py
from django.shortcuts import render
from django.http import HttpResponse
from HalfFull.forms import UserForm, PubForm#, #CrawlForm
from HalfFull.models import Pub, UserProfile

from django.contrib.auth import authenticate, login 
from django.http import HttpResponse 
from django.urls import reverse 
from django.shortcuts import redirect
# Create your views here.

def home(request):
    context_dict = {}
    return render(request, 'HalfFull/home.html', context=context_dict)

def about(request):
    context_dict = {}
    return render(request, 'HalfFull/about.html', context=context_dict)

def contact(request):
    context_dict = {}
    return render(request, 'HalfFull/contact.html', context=context_dict)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('HalfFull:home'))
            else:
                return HttpResponse("Your HalfFull account is disabled.")
                
        else:
            print(f"Invalid login details: {username}, {password}") 
            return HttpResponse("Invalid login details supplied.")
            
    else:
        return render(request, 'HalfFull/login.html')

def signup(request):
    registered=False
    
    if request.method == 'POST':
    
        user_form = UserForm(request.POST)

    
        if user_form.is_valid(): 
            user = user_form.save() 
            user.set_password(user.password)
            user.save()
        
            registered=True
        else:
            print(user_form.errors)
            
    else:
        user_form = UserForm()
        
    return render(request, 'HalfFull/signup.html', context = {'user_form': user_form, 'registered': registered})

def userpage(request):
    context_dict = {}
    return render(request, 'HalfFull/userpage.html', context=context_dict)

def make_a_crawl(request):
    context_dict = {}
    
    userprofile = UserProfile(user=request.user)
    userprofile.save()
    crawls = userprofile.crawl.all()
    context_dict['crawls'] = crawls
    
    return render(request, 'HalfFull/make_a_crawl.html', context=context_dict)

def pub_list(request):
    context_dict = {}
	
    pubs = Pub.objects.all()
    context_dict['pubs'] = pubs
    
    user1 = request.user
    
    if request.method == 'POST':
        name = pub.name
        atmosphere=pub.atmosphere
        service=pub.service
        drinks=pub.drinks
        picture=pub.picure
        crawl1 = pub(name = pub.name, atmosphere=pub.atmosphere, service=pub.service, drinks=pub.drinks, picture=pub.picure)
        crawl1.save()
        user1.crawl.add(crawl1)
	
    return render(request, 'HalfFull/pub_list.html', context=context_dict)
    
def add_a_pub(request):
    form = PubForm
    
    if request.method == 'POST':
        form = PubForm(request.POST)
        
        if form.is_valid():
            form.save(commit=True)
            return redirect('/HalfFull/home/')
        else:
            print(form.errors)
            
    return render(request, 'HalfFull/add_a_pub.html', {'form':form})    
    

templates/HalfFull/about.html
{% extends 'HalfFull/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
<div class="jumbotron">
  <h1 class="display-4">About HalfFull</h1>
  <p class="lead">HalfFull is a Web App which allows you to find pubs which suit your interests and keep track of them by adding the mto your own personal Crawl.
  Created as a second year group project by Glasgow University Computing Science students, Ben Lynch and Drew Galloway, in 2020</p>
  <hr class="my-4">
</div>
{% endblock %}

templates/HalfFull/add_a_pub.html
{% extends 'HalfFull/base.html' %} 
{% load staticfiles %}

{% block title_block %} 
	add a pub 
{% endblock %}

{% block body_block %}

{% if user.is_authenticated %}

  <div class="jumbotron p-4">
	<div class="container">
	<h1 class="jumbotron heading">Add a Pub</h1>
	<p class="lead">your local pubs not already on HalfFull, why not add them here!</p>
	</div>
  </div>
  <div class="container">
  <div class = "row">
    <form role="form "id="pub" method="post" action="{% url 'HalfFull:add_a_pub' %}">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br />
        {{ field }}<br />
		<div class="p-2"></div>
      {% endfor %}
	  <br />
      <button class="btn btn-primary" type="submit" name="submit">
		Add Pub
	  </button>
	  <div class="p-5"></div>
    </form>
  </div>
  </div>
  
  {% else %}
  <div class="jumbotron p-4">
	<div class="container">
	<h1 class="jumbotron heading">Sorry!</h1>
	<p class="lead">you must be logged in to add pubs to HalfFull</p>
	</div>
  </div>
  {% endif %}
{% endblock %}

templates/HalfFull/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Half Full</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pages
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
				  <a class="dropdown-item" href="/HalfFull/">Home</a>
                  <a class="dropdown-item" href="/HalfFull/userpage/">Profile</a>
                  <a class="dropdown-item" href="/HalfFull/pub_list/">Pubs</a>
				  <a class="dropdown-item" href="/HalfFull/add_a_pub/">Add a Pub</a>
                  <a class="dropdown-item" href="/HalfFull/make_a_crawl/">Make a Crawl</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/HalfFull/about/">About</a>
                  <a class="dropdown-item" href="/HalfFull/contact/">Contact</a>
                </div>
              </li>
          <ul class="nav navbar-nav">
            <li class="navbar-brand" href="#">Half Full</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/HalfFull/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="/HalfFull/login/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        </div>
      </nav> 
    <h1></h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	
	{% block body_block %}
    {% endblock %}
		
  </body>
</html>

templates/HalfFull/contact.html
{% extends 'HalfFull/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Contact
{% endblock %}

{% block body_block %}
<div class="jumbotron">
  <h1 class="display-4">Contact</h1>
  <p class="lead">If you wish to reach us, you can email Ben Lynch via his student email at Glasgow university, 2381564l@student.gla.ac.uk</p>
  <hr class="my-4">
</div>
{% endblock %}

templates/HalfFull/home.html
{% extends 'HalfFull/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %} 
<div class="jumbotron p-4">
	<div class="container">
	<h1 class="jumbotron heading">Welcome to HalfFull</h1>
	<p class="lead">The app for all your drinking needs</p>
	{% if user.is_authenticated %}
		<p class="lead">welcome back {{ user.username }}</p>
	{% endif %}
	</div>
  </div>
  
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
	  <a href="/HalfFull/make_a_crawl/">
      <img src="/static/images/pub_crawl.jpg" class="d-block w-100" alt="pub crawl">
      <div class="carousel-caption d-none d-md-block">
        <h5>Plan your night out</h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
	<a href="/HalfFull/pub_list/">
      <img src="/static/images/pubs.jpg" class="d-block w-100" alt="pubs">
      <div class="carousel-caption d-none d-md-block">
        <h5>Find New Pubs</h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
	  <a href="/HalfFull/signup">
      <img src="/static/images/profile.jpg" class="d-block w-100" alt="profile">
      <div class="carousel-caption d-none d-md-block">
        <h5>SignUp to become part of HalfFull</h5>
        <p></p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% endblock %}

templates/HalfFull/login.html
{% extends 'HalfFull/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Log In
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
	<div class="container">
	<h1 class="jumbotron heading">Login</h1>
	<p class="lead">Login to HalfFull here!</p>
	</div>
  </div>
 {% if user.is_authenticated %}
	You are already logged in
{% else %}
<div class="container">
<form id="login_form" method="post" action="{% url 'HalfFull:login' %}">
	{% csrf_token %} 
	<label for="inputUsername" class="sr-only">Username</label> 
	Username: <input type="text" name="username" value="" size="50" id="id_username" class="form-control" placeholder="Username" required autofocus/> 
	<br /> 
	<label for="inputPassword" class="sr-only">Password</label> 
	Password: <input type="password" name="password" value="" size="50" id="id_password" class="form-control" placeholder="Password" required/> 
	<br /> 
	<button class="btn btn-lg btn-primary btn-block" type="submit" value="submit">Sign In</button> 
</form>
</div>
{% endif %}
{% endblock %}

templates/HalfFull/make_a_crawl.html
{% extends 'HalfFull/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Make a Crawl
{% endblock %}


{% block body_block %}
{% if user.is_authenticated %}
  <div class="jumbotron p-4">
	<div class="container">
	<h1 class="jumbotron heading">Your crawl</h1>
	<p class="lead">pubs you add to your crawl will be shown here</p>
	</div>
  </div>
  {% else %}
  <div class="jumbotron p-4">
	<div class="container">
	<h1 class="jumbotron heading">Sorry!</h1>
	<p class="lead">you must be logged in to add pubs to HalfFull</p>
	</div>
  </div>
  {% endif %}
{% endblock %}

templates/HalfFull/pub_list.html
{% extends 'HalfFull/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Pub List
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
	<div class="container">
		<h1 class="jumbotron heading">Pubs</h1>
	</div>
	</div>
	
	<div>
	{% for pub in pubs %}
		<div class="container">
		
		<div class="card" style="width: 18rem;">
        <img src="{{pub.picture}}" class="card-img-top" alt="...">
        <div class="card-body">
        <h5 class="card-title">{{ pub.name }}</h5>
        <p class="card-text">Drinks rating: {{ pub.drinks }}</p>
		<p class="card-text">Drinks rating: {{ pub.atmosphere }}</p>
		<p class="card-text">Drinks rating: {{ pub.service }}</p>
		{% if user.is_authenticated %}
        <button class="btn btn-primary" type="submit" name="submit">
		Add to Crawl
	  </button>
		{% endif %}
		</div>
</div>
		</div>
	{% endfor %}
	</div>
{% endblock %}

templates/HalfFull/signup.html
{% extends 'HalfFull/base.html' %}
{% load staticfiles %}

{% block title_block %}
    SignUp
{% endblock %}

{% block body_block %}

{% if registered %}
<strong>thank you for registering!</strong>
{% else %}
<div class="jumbotron p-4">
	<div class="container">
	<h1 class="jumbotron heading">Sign Up for HalfFull</h1>
	<p class="lead">Why not become a member of HalfFull here!</p>
	</div>
  </div>
  <div class="container">
  <div class = "row">
      <form id="user_form" method="post" action="{% url 'HalfFull:signup' %}"
	enctype="multipart/form-data">
	
	{% csrf_token %}
	
	{{ user_form.as_p }} </ br>
		<div class="p-2"></div>

	  <br />
      <button class="btn btn-primary" type="submit" name="submit">
		Sign Up
	  </button>
	  <div class="p-5"></div>
    </form>
  </div>
  </div>
  {% endif %}
{% endblock %}

templates/HalfFull/userpage.html
{% extends 'HalfFull/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Userpage
{% endblock %}

{% block body_block %}
{% if user.is_authenticated %}
   <div class="jumbotron p-4">
      <h1 class="display-4">Your Profile</h1>
      <p class="lead">Username: {{ user.username }} </p>
   </div>
   
   <div class="container">
   <p class="lead">From here you can add a new pub, or make a crawl of your favourite pubs.</p>
   </div>
   
   <div class="container">
      <a href="{% url 'HalfFull:add_a_pub' %}">Add a New Pub</a><br />
      <a href="{% url 'HalfFull:make_a_crawl' %}">Make a New Crawl</a>
   </div>
{% else %}
   <div class="jumbotron p-4">
	  <h1 class="display-4">Sorry!</h1>
      <p class="lead">you must be logged in to view your profile</p>
   </div>
{% endif %}
{% endblock %}